<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INPUHJPC10986" ignored="0" name="Test" tests="1" failures="1" timestamp="12 Dec 2018 20:44:20 GMT" time="0.026" errors="0">
  <testcase name="f" time="0.009" classname="TestPackage.NewTest1">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
	at TestPackage.NewTest1.f(NewTest1.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
